theme: jekyll-theme-tactile
title: Rate-A-Dog: The dog-rating tool of the future.
description: Harness the power of The Cloud and Artificial Intelligence to recieve an algorithmically accurate rating of any dog you can concieve.
